String labelBottomNavigashion = '';
String labelBottomNavigashionTransactionlist = '';
String labelBottomNavigashionShoplist = '';
String shoplist = 'Shopping List';
String budget = 'You still can spend';
String transactions = "Transactions";
String textSettingsCounts = 'currencys';
String textSettingsBudget = 'budget';
String textSettingShopList = 'shopping lists';
String textSettings = 'settings';
String transactionHeaderText = 'Accounts'; //
String addNewProductText = 'Add new product';
String deleteProductText = 'Delete product?';
String approveText = 'Approve'; //''Income from
String deleteTransactionText = 'Delete transaction?';
String deleteAccountText = 'Delete account?';
String deleteAccountTransactionText1 = 'You closed the account,';
String deleteAccountTransactionText2 = 'sum was debited';
String incomeFromText = 'Income from'; //Forward from
String expenseToText = 'Expense to'; //''Forward from
// String isText = 'is';
String forwardFromText = 'Forward from'; //to
String forwardToText = 'to'; //My money
String myMoneyText = "My money"; //Input new sum
String inputNewSumText = 'Input new sum'; //
String deleteShopListText = 'Delete Shopping list?';
String deleteText = 'Delete';
String editeText = 'Edite';
String add = "add";
String selectNewCategory = "select new inputed category";
String selectCategory = "Select category";
String toAccount = "to account";
String selectAccount = "Select account";
String fromAccount = "from account";
String sumToAccount = "sum to account";
